version: "2.1"
services:
 heimdall:
   image: lscr.io/linuxserver/heimdall:latest
   container_name: heimdall # name of container
   environment:
     - PUID=1000 # User ID of your User
     - PGID=1000 # Group ID of your User
     - TZ=Etc/UTC # Your Timezone
   volumes:
     - /home/$(whoami)/heimdall:/config # Path where you want your config file Machine:Container
   #networks:
     #- Web # Adds this service to the network Web, that network config for this whole .yml is at the bottom
   ports:
     - 8001:80 # Machine(outside, you can change):Container(inside, this cannot change)
     - 4430:443 # Machine(outside, you can change):Container(inside, this cannot change)
   restart: unless-stopped # will reboot and keep alive unless manually stopped
#networks:
 #Web: # Network Name
   #external: true # external access out and to include other containers locally


#uncomment the network sections if you manually set a docker network.  You can change the name Web to whatever that network is.
