version: "2.1"
services:
 radarr:
   image: lscr.io/linuxserver/radarr:latest
   container_name: radarr # name of container
   environment:
     - PUID=1000 # User ID of your User
     - PGID=1000 # Group ID of your User
     - TZ=Etc/UTC # Your Timezone
   volumes:
     - /home/$(whoami)/sonarr:/config # Path where you want your config file - Machine:Container
     - /home/$(whoami)/media:/media # Path where you want your media files - Machine:Container
     - /home/$(whoami)/downloads:/downloads # Path where you want your download files - Machine:Container
   #networks:
     #- Web # Adds this service to the network Web, that network config for this whole .yml is at the bottom
   ports:
     - 7878:7878 # Machine(outside, you can change):Container(inside, this cannot change)
   restart: unless-stopped # will reboot and keep alive unless manually stopped
#networks:
 #Web: # Network Name
   #external: true # external access out and to include other containers locally


#uncomment the network sections if you manually set a docker network.  You can change the name Web to whatever that network is.
